services:
  postgres:
    build: 
      context: ./postgres
      dockerfile: Dockerfile
    image: alexflames77/custom-postgres-17:latest
    container_name: vtb_postgres
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  api:
    build: 
      context: ./app
      dockerfile: Dockerfile
    image: alexflames77/sql_analyzer:latest
    container_name: vtb_api
    environment:
      - DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
    ports:
      - "${API_PORT}:8000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock 
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
